# Lab Assignment 1

Once you finish the following tasks, please save this notebook and upload it to iCollege (Assignments > Lab Assignment 1).
You will lose 50% of the points if you fail to upload the file in the notebook format (.ipynb). In other words, do not change the format of the file.

This lab assignment will be graded based on whether your Python code achieves the objectives.

Please feel free to create more cells if needed.

## Assignment

#### 1. Create three lists (name, female, and age) that return the following information:

name

['Alice', 'Bob', 'Claire', 'Daniel']

female

[True, False, True, False]

age

[20, 25, 30, 35]

In [72]:
import numpy as np
import pandas as pd

In [73]:
name = ['Alice', 'Bob', 'Claire', 'Daniel']

In [74]:
female = [True, False, True, False]

In [75]:
age = [20, 25, 30, 35]

#### 2. Create numpy arrays for female and age lists. (two separate arrays)

In [76]:
arr_female = np.array(female)
arr_age = np.array(age)

arr_female
arr_age

array([20, 25, 30, 35])

In [77]:
arr_female

array([ True, False,  True, False])

In [78]:
arr_age

array([20, 25, 30, 35])

#### 3. Create a Python dictionary whose keys are "name", "female", and "age". The value of each of these keys should be the corresponding list created in 1.

In [79]:
column_names = ['name', 'female', 'age']
arr_name = np.array(name)
df = pd.DataFrame(np.vstack([arr_name, arr_female, arr_age]).T, columns=column_names)

table_dict = df.to_dict(orient='records')
table_dict

[{'name': 'Alice', 'female': 'True', 'age': '20'},
 {'name': 'Bob', 'female': 'False', 'age': '25'},
 {'name': 'Claire', 'female': 'True', 'age': '30'},
 {'name': 'Daniel', 'female': 'False', 'age': '35'}]

#### 4. Create a pandas dataframe from the Python dictionary you made in 3. The index of the dataframe should be the name column.

In [80]:
frame=pd.DataFrame.from_dict(table_dict)
frame

name female age
0   Alice   True  20
1     Bob  False  25
2  Claire   True  30
3  Daniel  False  35

#### 5. Retrieve and print out the row of 'Bob' from the pandas dataframe.

In [81]:
frame.iloc[1]

name        Bob
female    False
age          25
Name: 1, dtype: object

#### 6. Obtain and print out the mean of the age column from the dataframe.

Hint: try using `mean()` method of the dataframe. It works similar to `describe()` method.

In [82]:
frame["age"] = pd.to_numeric(frame.age, errors='coerce')
frame.mean()

age    27.5
dtype: float64

#### 7. Retrieve and print out Claire's age from the data frame.

In [83]:
frame['age'][2]

30